---
- name: create consul directory
  file: >
    state=directory
    path={{ item }}
  sudo: yes
  with_items:
    - "{{ consul_home }}"
    - "{{ consul_home }}/data"
    - "{{ consul_home }}/bin"
    - "{{ consul_config_dir }}"
    - "{{ consul_download_folder }}"

- name: download consul
  get_url: >
    url={{consul_download}}
    dest={{consul_download_folder}}
  register: consul_was_downloaded

- name: copy and unpack
  unarchive: >
    src={{ consul_download_folder }}/{{ consul_archive }}
    dest={{ consul_home }}/bin
    copy=no
  sudo: yes
  when: consul_was_downloaded|changed

- name: add consul to PATH
  template: >
    src=consul.sh.j2
    dest=/etc/profile.d/consul.sh
    owner=root
    group=root
    mode=0755
  sudo: yes

- name: create consul group
  group: >
    name={{consul_group}}
    state=present
  sudo: yes

- name: create consul user
  user: >
    name={{consul_user}}
    group={{consul_group}}
  sudo: yes

- name: set permissions
  file: >
    state=directory
    path={{consul_home}}
    owner={{consul_user}}
    group={{consul_group}}
    recurse=yes
  sudo: yes

- name: setup upstart script
  template: >
    src=consul.conf.j2
    dest=/etc/init/consul.conf
    owner={{consul_user}}
    group={{consul_group}}
    mode=0755
  sudo: yes
